#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = -IF:\\Program\\cpptcl-1.1.3 -IF:\\Program\\boost_1_59_0 -IF:\\Program\\Tcl\\include
CFLAGS = -Wall -std=c++11
RESINC = 
LIBDIR = -LF:\\Program\\Tcl\\lib
LIB = 
LDFLAGS = -ltcl86

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -D__DEBUG__
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\reversi.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -D__NDEBUG__
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\reversi.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\cpptcl.o $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\reversi.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\cpptcl.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\reversi.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\cpptcl.o: cpptcl.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c cpptcl.cc -o $(OBJDIR_DEBUG)\\cpptcl.o

$(OBJDIR_DEBUG)\\main.o: main.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cc -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\reversi.o: reversi.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c reversi.cc -o $(OBJDIR_DEBUG)\\reversi.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\cpptcl.o: cpptcl.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c cpptcl.cc -o $(OBJDIR_RELEASE)\\cpptcl.o

$(OBJDIR_RELEASE)\\main.o: main.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cc -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\reversi.o: reversi.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c reversi.cc -o $(OBJDIR_RELEASE)\\reversi.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

